### ISSUE TITLE
Gulp Watch Compiling CSS to incorrect folder

### ISSUE THREAD

**Issue by jrglass** [understrap/understrap-child#113]
After running `Gulp Watch` for the firs time, it compiles the `_child_theme.scss` > `child_theme.css` in both the css folder (which is correct) but also in the current folder of the `_child_theme.scss` (/sass/theme/).

```
So, the next time I try to save the `_child_theme.scss` file it outputs this error: 

{ Error: sass/child-theme.scss
Error: It's not clear which file to import for '@import "theme/child_theme"'.
       Candidates:
         theme/_child_theme.scss
         theme/_child_theme.css
       Please delete or rename all but one of these files.
        on line 11 of sass/child-theme.scss
>> @import "theme/child_theme";  // <--------- Add your styles into this file
   ^
    at options.error (/Users/jrglass/Sites/20.freeskier.dev/wp-content/themes/understrap-child/node_modules/node-sass/lib/index.js:291:26)
  status: 1,
  file: '/Users/jrglass/Sites/20.freeskier.dev/wp-content/themes/understrap-child/sass/child-theme.scss',
  line: 11,
  column: 1,
  message: 'sass/child-theme.scss\nError: It\'s not clear which file to import for \'@import "theme/child_theme"\'.\n       Candidates:\n         theme/_child_theme.scss\n         theme/_child_theme.css\n       Please delete or rename all but one of these files.\n        on line 11 of sass/child-theme.scss\n>> @import "theme/child_theme";  // <--------- Add your styles into this file\n   ^\n',
  formatted: 'Error: It\'s not clear which file to import for \'@import "theme/child_theme"\'.\n       Candidates:\n         theme/_child_theme.scss\n         theme/_child_theme.css\n       Please delete or rename all but one of these files.\n        on line 11 of sass/child-theme.scss\n>> @import "theme/child_theme";  // <--------- Add your styles into this file\n   ^\n',
  messageFormatted: '\u001b[4msass/child-theme.scss\u001b[24m\nError: It\'s not clear which file to import for \'@import "theme/child_theme"\'.\n       Candidates:\n         theme/_child_theme.scss\n         theme/_child_theme.css\n       Please delete or rename all but one of these files.\n        on line 11 of sass/child-theme.scss\n>> @import "theme/child_theme";  // <--------- Add your styles into this file\n   ^\n',
  messageOriginal: 'It\'s not clear which file to import for \'@import "theme/child_theme"\'.\nCandidates:\n  theme/_child_theme.scss\n  theme/_child_theme.css\nPlease delete or rename all but one of these files.\n',
  relativePath: 'sass/child-theme.scss',
  name: 'Error',
  stack: 'Error: sass/child-theme.scss\nError: It\'s not clear which file to import for \'@import "theme/child_theme"\'.\n       Candidates:\n         theme/_child_theme.scss\n         theme/_child_theme.css\n       Please delete or rename all but one of these files.\n        on line 11 of sass/child-theme.scss\n>> @import "theme/child_theme";  // <--------- Add your styles into this file\n   ^\n\n    at options.error (/Users/jrglass/Sites/20.freeskier.dev/wp-content/themes/understrap-child/node_modules/node-sass/lib/index.js:291:26)',
  showStack: false,
  showProperties: true,
  plugin: 'gulp-sass' }
```

Is there a way to update the `gulpfile.js` file so it doesn't do this? 
I have to manually delete the _child_theme.css file before saving every time so I don't run into this error.
This hasn't been an issue in any other installs of the understrap-child theme I've worked with.

**Comment by axlright** [comment]
Does your `theme/_child_theme.scss` file have an underscore in front of it? Looking at your error message, there shouldn't be a file called `file: '/Users/jrglass/Sites/20.freeskier.dev/wp-content/themes/understrap-child/sass/child-theme.scss',` - that file should be `sass/_child-theme.scss`

**Comment by jrglass** [comment]
Yes, the file has an underscore before it.

What's happening is that when I save that file it's creating another file without the underscore in the same folder, thus causing the error.

**Comment by axlright** [comment]
That's not supposed to happen. That doesn't happen for me. So something is off with your gulp setup.

You can use regular command line Sass to compile, something like `sass watch scss:css` though I'm writing that from memory and usually get stuff like that wrong from memory.

Do you have Sass installed as a command line tool?

**Comment by Thomas-A-Reinert** [comment]
I assume that has been solved by now due to no feedback since nearly half a year. Also cannot reproduce it.

Feel free to reopen.
