### ISSUE TITLE
Error on gulp copy-assets after npm install

### ISSUE THREAD

**Issue by grandmanitou** [understrap/understrap-child#208]
```
assert.js:42
  throw new errors.AssertionError({
  ^

AssertionError [ERR_ASSERTION]: Task function must be specified
    at Gulp.set [as _setTask] (/Users/guillaumep/Sites/www/wp-content/themes/understrap-child/node_modules/undertaker/lib/set-task.js:10:3)
    at Gulp.task (/Users/guillaumep/Sites/www/wp-content/themes/understrap-child/node_modules/undertaker/lib/task.js:13:8)
    at Object.<anonymous> (/Users/guillaumep/Sites/www/wp-content/themes/understrap-child/gulpfile.js:72:6)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)

```

**Comment by 0dp** [comment]
what is the output of `gulp -v`

**Comment by grandmanitou** [comment]
I dont understand. 
After a reboot and full reinstall (node, npm, gulp) it is working now with no error.
You can close this issue. Thank you.

**Comment by 0dp** [comment]
your global gulp install was probably not up to date.
`gulp -v` is a command to check what version of gulp you have installed on your system.

You can close the issue yourself 👍

**Comment by AleCss81** [comment]
I have the same problem and I can't resolve it.

gulp -v

CLI version 2.1.0
Local version 4.0.0

**Comment by 0dp** [comment]
You need to downgrade your local gulp version to 3.9
You might also need to downgrade CLI version

**Comment by AleCss81** [comment]
Ok thanks, and how do I can downgrade gulp?
