### ISSUE TITLE
Error using gulpfile.js

### ISSUE THREAD

**Issue by bene82** [understrap/understrap-child#244]
I'm getting this error using the gulpfile.js and launching **gulp watch** command:

Node version: 12.12.0
Gulp version: 3.9.1

`gulp watch
fs.js:27
const { Math, Object } = primordials;
                         ^

ReferenceError: primordials is not defined
    at fs.js:27:26
    at req_ (/Users/bforastiere/Local Sites/auvisa/app/public/wp-content/themes/auvisa/node_modules/natives/index.js:143:24)
    at Object.req [as require] (/Users/bforastiere/Local Sites/auvisa/app/public/wp-content/themes/auvisa/node_modules/natives/index.js:55:10)
    at Object.<anonymous> (/Users/bforastiere/Local Sites/auvisa/app/public/wp-content/themes/auvisa/node_modules/vinyl-fs/node_modules/graceful-fs/fs.js:1:37)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:849:19)
    at require (internal/modules/cjs/helpers.js:74:18)`

The gulpfile contained in understrap theme works fine.

**Comment by joneldiablo** [comment]
I have this error after npm install
I try execute npm run postinstall but this error its happen to

**Comment by Thomas-A-Reinert** [comment]
Understrap uses npm Version 10.x. If you need to use different version over different projects please use [nvm](https://github.com/nvm-sh/nvm)

**Comment by axlright** [comment]
@Thomas-A-Reinert I think you mean *Node* version 10.x?

@joneldiablo  and @bene82 I'll say that I am also still struggling to get the right combination together to get all the `npm update` and `npm install` errors to go away. Using Node version 10.19.0 is one ingredient.
