### ISSUE TITLE
npm install problem

### ISSUE THREAD

**Issue by MoW187** [understrap/understrap-child#252]
I downloaded the latest version of node js, and the latest version of understrap and the latest version of understrap-child. When i run the npm install i'm getting an error message. With witch version of node will work the understrap?

**Comment by fschoenfeldt** [comment]
try using latest node 10, install and then it should work. I also updated the dependencies using `ncu -u`

```
frederik@frederik-G750JW:~/fschoenfeldt.de/understrap-child-master$ yarn
yarn install v1.17.3
[1/4] Resolving packages...
warning popper.js@1.16.1: You can find the new Popper v2 at @popperjs/core, this package is dedicated to the legacy v1
[2/4] Fetching packages...
info fsevents@1.2.7: The platform "linux" is incompatible with this module.
info "fsevents@1.2.7" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning " > bootstrap@4.4.1" has unmet peer dependency "jquery@1.9.1 - 3".
warning "understrap > bootstrap@4.3.1" has unmet peer dependency "jquery@1.9.1 - 3".
[4/4] Building fresh packages...
[1/8] ⠄ gifsicle
[-/8] ⠄ waiting...
[-/8] ⡀ waiting...
[8/8] ⡀ understrap
error /home/frederik/fschoenfeldt.de/understrap-child-master/node_modules/understrap: Command failed.
Exit code: 1
Command: gulp copy-assets
Arguments: 
Directory: /home/frederik/fschoenfeldt.de/understrap-child-master/node_modules/understrap
Output:
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'gulp-babel'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/frederik/fschoenfeldt.de/understrap-child-master/node_modules/understrap/gulpfile.js:5:13)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
```

even with that, I'm able to run the tasks important for me (`gulp styles`)

**Comment by Thomas-A-Reinert** [comment]
Something like 8.x of node should do. Don´t use 10.x. You may try, but you may fail ;)

**Comment by lukababu** [comment]
Having issues. Have the latest version of node.js installed. Using Windows 10 and Phpstorm, but tried running npm install in PowerShell without luck.

`c:\users\l_ire\phpstormprojects\st. aidan\node_modules\node-sass\src\create_string.cpp(17): error C2664: 'v8::String::Utf8Value::Utf8Value(const v8::String::Utf8Value &)': cannot convert argument 1 from 'v8::Local<v8::Value>' to 'const v8::String::Utf8Value &' [C:\Users\l_ire\PhpstormProjects\St. Aidan\node_modules\node-sass\build\binding.vcxproj]
 `

```
"C:\Users\l_ire\PhpstormProjects\St. Aidan\node_modules\node-sass\build\binding.sln" (default target) (1) ->
"C:\Users\l_ire\PhpstormProjects\St. Aidan\node_modules\node-sass\build\binding.vcxproj.metaproj" (default target) (2) ->
"C:\Users\l_ire\PhpstormProjects\St. Aidan\node_modules\node-sass\build\binding.vcxproj" (default target) (4) ->
(ClCompile target) ->
  c:\users\l_ire\phpstormprojects\st. aidan\node_modules\node-sass\src\create_string.cpp(17): error C2664: 'v8::String::Utf8Value::Utf8Value(const v8::String::Utf8Value &)': cannot convert argument 1 from 'v8::Local<v8::Value>' to 'const v8::String::Utf8Value &' [C:\Users\l_ire\PhpstormProjects\St. Aidan\node_modules\node-sass\build\binding.vcxproj]

    16 Warning(s)
    1 Error(s)

Time Elapsed 00:00:17.24
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\l_ire\PhpstormProjects\St. Aidan\node_modules\node-gyp\lib\build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:311:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Windows_NT 10.0.18363
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\l_ire\\PhpstormProjects\\St. Aidan\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd C:\Users\l_ire\PhpstormProjects\St. Aidan\node_modules\node-sass
gyp ERR! node -v v12.16.1
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
Build failed with error code: 1
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.11.0 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@4.11.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

```

Any help with this is much appreciated!

Attached is the full log file:
[2020-03-22T19_11_22_624Z-debug.log](https://github.com/understrap/understrap-child/files/4366071/2020-03-22T19_11_22_624Z-debug.log)

**Comment by lukababu** [comment]
Ok had to uninstall the latest version and then install [Node 8.16.2](https://nodejs.org/download/release/v8.16.2/node-v8.16.2-x64.msi). Works now...

**Comment by Thomas-A-Reinert** [comment]
I´d recommend using something like https://github.com/nvm-sh/nvm if you need different node versions on various projects..

**Comment by Thomas-A-Reinert** [comment]
Add on: using nvm you may try and iterate the version on your project.
