### ISSUE TITLE
error: no matching function for call to ‘v8::String

### ISSUE THREAD

**Issue by allanext** [understrap/understrap-child#268]
Hi all,

i'm getting the following error with `npm install`; the problem is only on the understrap-child not on understrap main theme.

I'm using node v12.16.3 on Centos 7

```
s/src/util.o Release/obj.target/libsass/src/libsass/src/values.o
  rm -rf "Release/sass.a" && cp -af "Release/obj.target/src/sass.a" "Release/sass.a"
  g++ '-DNODE_GYP_MODULE_NAME=binding' '-DUSING_UV_SHARED=1' '-DUSING_V8_SHARED=1' '-DV8_DEPRECATION_WARNINGS=1' '-DV8_DEPRECATION_WARNINGS' '-DV8_IMMINENT_DEPRECATION_WARNINGS' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-D__STDC_FORMAT_MACROS' '-DOPENSSL_NO_PINSHARED' '-DOPENSSL_THREADS' '-DBUILDING_NODE_EXTENSION' -I/home/centos/.node-gyp/12.16.3/include/node -I/home/centos/.node-gyp/12.16.3/src -I/home/centos/.node-gyp/12.16.3/deps/openssl/config -I/home/centos/.node-gyp/12.16.3/deps/openssl/openssl/include -I/home/centos/.node-gyp/12.16.3/deps/uv/include -I/home/centos/.node-gyp/12.16.3/deps/zlib -I/home/centos/.node-gyp/12.16.3/deps/v8/include -I../../nan -I../src/libsass/include  -fPIC -pthread -Wall -Wextra -Wno-unused-parameter -m64 -O3 -fno-omit-frame-pointer -fno-rtti -fno-exceptions -std=gnu++1y -std=c++0x -MMD -MF ./Release/.deps/Release/obj.target/binding/src/binding.o.d.raw   -c -o Release/obj.target/binding/src/binding.o ../src/binding.cpp
  g++ '-DNODE_GYP_MODULE_NAME=binding' '-DUSING_UV_SHARED=1' '-DUSING_V8_SHARED=1' '-DV8_DEPRECATION_WARNINGS=1' '-DV8_DEPRECATION_WARNINGS' '-DV8_IMMINENT_DEPRECATION_WARNINGS' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-D__STDC_FORMAT_MACROS' '-DOPENSSL_NO_PINSHARED' '-DOPENSSL_THREADS' '-DBUILDING_NODE_EXTENSION' -I/home/centos/.node-gyp/12.16.3/include/node -I/home/centos/.node-gyp/12.16.3/src -I/home/centos/.node-gyp/12.16.3/deps/openssl/config -I/home/centos/.node-gyp/12.16.3/deps/openssl/openssl/include -I/home/centos/.node-gyp/12.16.3/deps/uv/include -I/home/centos/.node-gyp/12.16.3/deps/zlib -I/home/centos/.node-gyp/12.16.3/deps/v8/include -I../../nan -I../src/libsass/include  -fPIC -pthread -Wall -Wextra -Wno-unused-parameter -m64 -O3 -fno-omit-frame-pointer -fno-rtti -fno-exceptions -std=gnu++1y -std=c++0x -MMD -MF ./Release/.deps/Release/obj.target/binding/src/create_string.o.d.raw   -c -o Release/obj.target/binding/src/create_string.o ../src/create_string.cpp
../src/create_string.cpp: In function ‘char* create_string(Nan::MaybeLocal<v8::Value>)’:
../src/create_string.cpp:17:37: error: no matching function for call to ‘v8::String::Utf8Value::Utf8Value(v8::Local<v8::Value>&)’
   v8::String::Utf8Value string(value);
                                     ^
../src/create_string.cpp:17:37: note: candidate is:
In file included from /home/centos/.node-gyp/12.16.3/include/node/node.h:67:0,
                 from ../../nan/nan.h:53,
                 from ../src/create_string.cpp:1:
/home/centos/.node-gyp/12.16.3/include/node/v8.h:3135:5: note: v8::String::Utf8Value::Utf8Value(v8::Isolate*, v8::Local<v8::Value>)
     Utf8Value(Isolate* isolate, Local<v8::Value> obj);
     ^
/home/centos/.node-gyp/12.16.3/include/node/v8.h:3135:5: note:   candidate expects 2 arguments, 1 provided
make: *** [Release/obj.target/binding/src/create_string.o] Error 1
make: Leaving directory `/var/www/html/web_app.org/wp-content/themes/understrap-child/node_modules/node-sass/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/var/www/html/web_app/wp-content/themes/understrap-child/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:310:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Linux 3.10.0-1127.8.2.el7.x86_64
gyp ERR! command "/home/centos/.nvm/versions/node/v12.16.3/bin/node" "/var/www/html/web_app/wp-content/themes/understrap-child/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /var/www/html/web_app/wp-content/themes/understrap-child/node_modules/node-sass
gyp ERR! node -v v12.16.3
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
Build failed with error code: 1
npm WARN bootstrap@4.3.1 requires a peer of jquery@1.9.1 - 3 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.11.0 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-sass@4.11.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/centos/.npm/_logs/2020-06-10T19_14_51_522Z-debug.log
```

is this related to nan https://github.com/nodejs/nan/issues/849 ?

**Comment by bacoords** [comment]
Please pull the latest version of the child theme (namely the package.json and gulp files), reinstall, and try again. Let us know if this works.
