### ISSUE TITLE
Issues with npm run watch in the understrap-child

### ISSUE THREAD

**Issue by sbcmeg** [understrap/understrap-child#364]
I have followed the setup instructions for undersrap-child, and have the parent understrap folder.

When I go to run `npm run watch`.

I get the following errors within terminal:

`> understrap-child@1.1.0 watch /Users/meg/htdocs/sbc/wp-content/themes/understrap-child
> npm-run-all --parallel watch-run-*

> understrap-child@1.1.0 watch-run-js /Users/meg/htdocs/sbc/wp-content/themes/understrap-child
> nodemon --watch src/js/ --ext js --exec "npm-run-all js"

> understrap-child@1.1.0 watch-run-css /Users/meg/htdocs/sbc/wp-content/themes/understrap-child
> nodemon --watch src/sass/ --ext scss --exec "npm-run-all css"

/Users/meg/htdocs/sbc/wp-content/themes/understrap-child/node_modules/update-notifier/index.js:58
			} catch {
			        ^

SyntaxError: Unexpected token {
    at new Script (vm.js:51:7)
    at createScript (vm.js:136:10)
    at Object.runInThisContext (vm.js:197:10)
    at Module._compile (internal/modules/cjs/loader.js:618:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
    at Module.load (internal/modules/cjs/loader.js:566:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
    at Function.Module._load (internal/modules/cjs/loader.js:498:3)
    at Module.require (internal/modules/cjs/loader.js:598:17)
    at require (internal/modules/cjs/helpers.js:11:18)
/Users/meg/htdocs/sbc/wp-content/themes/understrap-child/node_modules/update-notifier/index.js:58
			} catch {
			        ^

SyntaxError: Unexpected token {
    at new Script (vm.js:51:7)
    at createScript (vm.js:136:10)
    at Object.runInThisContext (vm.js:197:10)
    at Module._compile (internal/modules/cjs/loader.js:618:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
    at Module.load (internal/modules/cjs/loader.js:566:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
    at Function.Module._load (internal/modules/cjs/loader.js:498:3)
    at Module.require (internal/modules/cjs/loader.js:598:17)
    at require (internal/modules/cjs/helpers.js:11:18)
npmnpm  ERR!ERR!  codecode ELIFECYCLE
 ELIFECYCLE
npm ERR! errnonpm 1
 ERR! errno 1
npm ERR! understrap-child@1.1.0 watch-run-js: `nodemon --watch src/js/ --ext js --exec "npm-run-all js"`
npm ERR! Exit status 1
npmnpm  ERR! understrap-child@1.1.0 watch-run-css: `nodemon --watch src/sass/ --ext scss --exec "npm-run-all css"`
ERR!npm  
npmERR! ERR! Exit status 1
 Failed at the understrap-child@1.1.0 watch-run-js script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! 
npm ERR! Failed at the understrap-child@1.1.0 watch-run-css script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/meg/.npm/_logs/2022-10-27T10_48_01_929Z-debug.log

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/meg/.npm/_logs/2022-10-27T10_48_01_929Z-debug.log
ERROR: "watch-run-js" exited with 1.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! understrap-child@1.1.0 watch: `npm-run-all --parallel watch-run-*`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the understrap-child@1.1.0 watch script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:`

**Comment by bacoords** [comment]
Can you provide the results of `node -v` ?

**Comment by CarlosRios** [comment]
I was running into the same issue on a Mac, and realized that my default node is 8.10 I think. Updating node solved the issue.
